name: "allium_project"
version: "1.0"
config-version: 2
profile: allium_project

vars:
  blockchain: "sui"
  contract_address: "0x549e8b69270defbfafd4f94e17ec44cdbdd99820b33bda2278dea3b9a32d3f55::cert::CERT"
  start_date: "2024-01-01 00:00:00"
  end_date: "2024-11-30 23:59:59"
  enrich_chain: "ethereum"