"""create tables

Revision ID: 79633f42fd8c
Revises: 
Create Date: 2024-12-03 00:10:46.967475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79633f42fd8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_mapping_table',
    sa.Column('blockchain', sa.String(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('coin_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('blockchain', 'contract_address'),
    schema='prices_schema'
    )
    op.create_table('prices',
    sa.Column('coin_id', sa.String(), nullable=False),
    sa.Column('time_of_price', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('coin_id', 'time_of_price'),
    schema='prices_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices', schema='prices_schema')
    op.drop_table('coin_mapping_table', schema='prices_schema')
    # ### end Alembic commands ###
